import js from '@eslint/js';
import n from 'eslint-plugin-n';

export default [
    {
        ignores: ['node_modules/**'],
    },
    // Node.js backend
    {
        files: ['src/**/*.js'],
        plugins: { n },
        ...js.configs.recommended,
        rules: {
            ...js.configs.recommended.rules,
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-console': 'off',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'n/no-missing-require': 'error',
            'n/no-extraneous-require': 'error',
        },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                require: 'readonly',
                module: 'readonly',
                exports: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                console: 'readonly',
                fetch: 'readonly',
                URLSearchParams: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                setImmediate: 'readonly',
                URL: 'readonly',
            },
        },
    },
    // app.js — defines the shared helpers used by other browser scripts
    {
        files: ['public/js/app.js'],
        ...js.configs.recommended,
        rules: {
            ...js.configs.recommended.rules,
            'no-unused-vars': 'off',
            'no-console': 'off',
            'no-empty': ['error', { allowEmptyCatch: true }],
        },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                window: 'readonly',
                document: 'readonly',
                fetch: 'readonly',
                alert: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                URL: 'readonly',
                MutationObserver: 'readonly',
                prompt: 'readonly',
                Event: 'readonly',
                btoa: 'readonly',
            },
        },
    },
    // Browser JS — consumer scripts that use helpers from app.js
    {
        files: ['public/js/**/*.js'],
        ignores: ['public/js/app.js'],
        ...js.configs.recommended,
        rules: {
            ...js.configs.recommended.rules,
            // Functions called from HTML onclick attributes appear unused to ESLint
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^(edit|delete|toggle|test|remove|show)' }],
            'no-console': 'off',
            'no-empty': ['error', { allowEmptyCatch: true }],
        },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                window: 'readonly',
                document: 'readonly',
                fetch: 'readonly',
                alert: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                URL: 'readonly',
                MutationObserver: 'readonly',
                prompt: 'readonly',
                Event: 'readonly',
                btoa: 'readonly',
                // Shared helpers defined in app.js and loaded via <script> tags
                initNav: 'readonly',
                apiFetch: 'readonly',
                showAlert: 'readonly',
                showConfirm: 'readonly',
                escapeHtml: 'readonly',
                formatDate: 'readonly',
            },
        },
    },
];
