services:
  RegistryView:
    image: registryview:dev
    container_name: RegistryView-dev
    hostname: macbookair-RegistryView
    restart: unless-stopped

    mem_limit: 356m

    ports:
      - "3544:3544"

    environment:
      TZ: Europe/London
      PORT: 3544
      NODE_ENV: development
      NGINX_URL: https://RegistryView.internal

      AUTH_ENABLED: "true"
      UI_USERNAME: admin
      UI_PASSWORD: changeme

      SESSION_SECRET: change-me-to-a-long-random-string
      ENCRYPTION_KEY: change-me-to-a-long-random-string

      DATA_DIR: /app/data
      LOG_DIR: /app/logs
      LOG_LEVEL: info

    volumes:
      - /Users/Barry/DockerVolumes/RegistryView/data:/app/data
      - /Users/Barry/DockerVolumes/RegistryView/logs:/app/logs
